branches:
  only:
  - master
language: python
python: 3.5
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --exclude
  '.gitignore' --exclude 'upload.sh' --acl public-read --delete . s3://ipify-www
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E1JHMKBOJ3RGMV --paths '/*'
env:
  global:
  - secure: W28658ftQrE1Mfb/V6lKRwGT4pUcrRn0cH17WLvMFP6ypXIPXTU9S28OkGh3TpaZ+wrESqFVr5lQlph4Zu8sZe+bl50fj9VVxbsMIouHGxsZdcQd9wl9HEw9RdVRz/u+eDgrTmiRZ0z6J8BzIxUr9PjdCMoEpOx1CsJWYoVhU8M=
  - secure: cLrggTASe/mJhjyBSS5QJqj1F7x8qoVPhOgT6l5pNkUrdR0MSlUmWTtAJd5gkYOclbDwpqmYR04hbJ5kwdug3DIrTfff4AYf90LnxzxH8Vhsh1dOtUllp7/b8SBr9L9CvZWUYIVX4guI4czrzcIylJhFSnblWOu+OABmd9f5hIk=
